<a href="https://colab.research.google.com/github/ibrahimalmadhani/dataanalyst/blob/main/20260627_ETL_BMNRB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/MASTER ASET/20260128 - MASTER ASET AKTIF/daftar-aset-1.xlsx')
df1.drop(index=df1.index[0], axis=0, inplace=True)
df1.head()

,No,Jenis BMN,Kode Satker,Nama Satker,Kode Barang,NUP,Nama Barang,Status BMN,Merk,Tipe,...,Nama K/L,Nama E1,Nama Korwil,Kode Register,Lokasi Ruang,Jenis Identitas,No Identitas,No STNK,Nama Pengguna,Status PMK
1,1.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,1.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE518514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
2,2.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,2.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE519514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
3,3.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,3.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51A514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
4,4.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,4.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51B514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
5,5.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,5.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51C514CE0531661F20A6789,Belum berlokasi,NaN,NaN,stnk,NaN,NaN

In [ ]:
df2 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/MASTER ASET/20260128 - MASTER ASET AKTIF/daftar-aset-2.xlsx')
df2.drop(index=df2.index[0], axis=0, inplace=True)
df2.head()

,No,Jenis BMN,Kode Satker,Nama Satker,Kode Barang,NUP,Nama Barang,Status BMN,Merk,Tipe,...,Nama K/L,Nama E1,Nama Korwil,Kode Register,Lokasi Ruang,Jenis Identitas,No Identitas,No STNK,Nama Pengguna,Status PMK
1,300001.0,ALAT PERSENJATAAN,137040200692147000KD,Lapas Kelas IIA Bogor,3.090103e+09,8.0,Senapan Semi Otomatis,Aktif,PINDAD,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Jawa Barat,E2AAEF1BFB4512E7E0531161F20A8E10,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
2,300002.0,ALAT PERSENJATAAN,137040200692147000KD,Lapas Kelas IIA Bogor,3.090103e+09,9.0,Senapan Semi Otomatis,Aktif,PINDAD,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Jawa Barat,E2AAEF1BFB3612E7E0531161F20A8E10,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
3,300003.0,ALAT PERSENJATAAN,137040200692147000KD,Lapas Kelas IIA Bogor,3.090103e+09,10.0,Senapan Semi Otomatis,Aktif,PINDAD,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Jawa Barat,E2AAEF1BFB4A12E7E0531161F20A8E10,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
4,300004.0,ALAT PERSENJATAAN,137040200692147000KD,Lapas Kelas IIA Bogor,3.090103e+09,11.0,Senapan Semi Otomatis,Aktif,MAUSER,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Jawa Barat,E2AAEF1BFB3B12E7E0531161F20A8E10,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
5,300005.0,ALAT PERSENJATAAN,137040200692147000KD,Lapas Kelas IIA Bogor,3.090104e+09,1.0,Senjata Bahu/ Senjata Laras Panjang Lainnya,Aktif,PINDAD,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Jawa Barat,E2AAEF1BFB3D12E7E0531161F20A8E10,Belum berlokasi,NaN,NaN,NaN,NaN,NaN

In [ ]:
df3 = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/MASTER ASET/20260128 - MASTER ASET AKTIF/daftar-aset-3.xlsx')
df3.drop(index=df3.index[0], axis=0, inplace=True)
df3.head()

,No,Jenis BMN,Kode Satker,Nama Satker,Kode Barang,NUP,Nama Barang,Status BMN,Merk,Tipe,...,Nama K/L,Nama E1,Nama Korwil,Kode Register,Lokasi Ruang,Jenis Identitas,No Identitas,No STNK,Nama Pengguna,Status PMK
1,600001.0,MESIN PERALATAN NON TIK,137041200692778000KD,Lembaga Pembinaan Khusus Anak Kelas II Bandar ...,3.050201e+09,12.0,Sice,Aktif,NaN,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,E12B81F5E23F6B58E0531561F20AD777,KT.1.10 - Kasubsi Penilaian dan Klasifikasi,NaN,NaN,NaN,NaN,NaN
2,600002.0,MESIN PERALATAN NON TIK,137041200692778000KD,Lembaga Pembinaan Khusus Anak Kelas II Bandar ...,3.050201e+09,13.0,Sice,Aktif,NaN,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,E12B81F5E6426B58E0531561F20AD777,GB.1.1 - Gudang Bawah,NaN,NaN,NaN,NaN,NaN
3,600003.0,MESIN PERALATAN NON TIK,137041200692778000KD,Lembaga Pembinaan Khusus Anak Kelas II Bandar ...,3.050201e+09,14.0,Sice,Aktif,NaN,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,E12B81F5E7396B58E0531561F20AD777,KU.2.1 - Kepala LPKA,NaN,NaN,NaN,NaN,NaN
4,600004.0,MESIN PERALATAN NON TIK,137041200692778000KD,Lembaga Pembinaan Khusus Anak Kelas II Bandar ...,3.050201e+09,15.0,Sice,Aktif,NaN,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,E12B81F5E31E6B58E0531561F20AD777,KU.2.1 - Kepala LPKA,NaN,NaN,NaN,NaN,NaN
5,600005.0,MESIN PERALATAN NON TIK,137041200692778000KD,Lembaga Pembinaan Khusus Anak Kelas II Bandar ...,3.050201e+09,16.0,Sice,Aktif,NaN,NaN,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,E12B81F5E31F6B58E0531561F20AD777,Belum berlokasi,NaN,NaN,NaN,NaN,NaN

In [ ]:
df1 = pd.read_excel('/content/daftar-aset-1.xlsx')
df1.drop(index=df1.index[0], axis=0, inplace=True)
df1.head()
df2 = pd.read_excel('/content/daftar-aset-2.xlsx')
df2.drop(index=df2.index[0], axis=0, inplace=True)
df2.head()
df3 = pd.read_excel('/content/daftar-aset-3.xlsx')
df3.drop(index=df3.index[0], axis=0, inplace=True)
df3.head()

,No,Jenis BMN,Kode Satker,Nama Satker,Kode Barang,NUP,Nama Barang,Status BMN,Merk,Tipe,...,Nama K/L,Nama E1,Nama Korwil,Kode Register,Lokasi Ruang,Jenis Identitas,No Identitas,No STNK,Nama Pengguna,Status PMK
1,600001.0,MESIN PERALATAN NON TIK,137041200692572000KD,Rutan Kelas IIB Kotabumi,3.150206e+09,1.0,Sepatu Lapangan Lainnya,Aktif,Sepatu PDL Kelengkapan Huru-Hara,Sepatu PDL Kelengkapan Huru-Hara,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,459702925F3381E0E06366E7D80A6BD7,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
2,600002.0,MESIN PERALATAN NON TIK,137041200692572000KD,Rutan Kelas IIB Kotabumi,3.150206e+09,2.0,Sepatu Lapangan Lainnya,Aktif,Sepatu PDL Kelengkapan Huru-Hara,Sepatu PDL Kelengkapan Huru-Hara,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,459702925F3481E0E06366E7D80A6BD7,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
3,600003.0,MESIN PERALATAN NON TIK,137041200692572000KD,Rutan Kelas IIB Kotabumi,3.150206e+09,3.0,Sepatu Lapangan Lainnya,Aktif,Sepatu PDL Kelengkapan Huru-Hara,Sepatu PDL Kelengkapan Huru-Hara,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,459702925F3581E0E06366E7D80A6BD7,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
4,600004.0,MESIN PERALATAN NON TIK,137041200692572000KD,Rutan Kelas IIB Kotabumi,3.150206e+09,4.0,Sepatu Lapangan Lainnya,Aktif,Sepatu PDL Kelengkapan Huru-Hara,Sepatu PDL Kelengkapan Huru-Hara,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,459702925F3681E0E06366E7D80A6BD7,Belum berlokasi,NaN,NaN,NaN,NaN,NaN
5,600005.0,MESIN PERALATAN NON TIK,137041200692572000KD,Rutan Kelas IIB Kotabumi,3.150206e+09,5.0,Sepatu Lapangan Lainnya,Aktif,Sepatu PDL Kelengkapan Huru-Hara,Sepatu PDL Kelengkapan Huru-Hara,...,Kementerian Imigrasi dan Pemasyarakatan,Direktorat Jenderal Pemasyarakatan,Kantor Wilayah Ditjen Pemasyarakatan Lampung,459702925F3781E0E06366E7D80A6BD7,Belum berlokasi,NaN,NaN,NaN,NaN,NaN

In [ ]:
df4 = pd.concat([df1, df2, df3], ignore_index=True)
df4.head()

,No,Jenis BMN,Kode Satker,Nama Satker,Kode Barang,NUP,Nama Barang,Status BMN,Merk,Tipe,...,Nama K/L,Nama E1,Nama Korwil,Kode Register,Lokasi Ruang,Jenis Identitas,No Identitas,No STNK,Nama Pengguna,Status PMK
0,1.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,1.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE518514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
1,2.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,2.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE519514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
2,3.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,3.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51A514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
3,4.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,4.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51B514CE0531661F20A6789,Belum berlokasi,NaN,NaN,STNK,NaN,NaN
4,5.0,ALAT ANGKUTAN BERMOTOR,137010199694677000KP,Sekretariat Jenderal,3.020102e+09,5.0,Mini Bus ( Penumpang 14 Orang Kebawah ),Aktif,Toyota Rush,RUSH 1.5 S A/T GR 30,...,Kementerian Imigrasi dan Pemasyarakatan,Sekretariat Jenderal,Sekretariat Jenderal,EA2E420AE51C514CE0531661F20A6789,Belum berlokasi,NaN,NaN,stnk,NaN,NaN

In [ ]:
df4.columns = df4.columns.str.replace(' ', '_').str.replace('/', '_')

In [ ]:
rusak_berat_count = df4[df4['Kondisi'] == 'Rusak Berat'].shape[0]
print(f"Total rows with Kondisi 'Rusak Berat': {rusak_berat_count}")

rusak_ringan_count = df4[df4['Kondisi'] == 'Rusak Ringan'].shape[0]
print(f"Total rows with Kondisi 'Rusak Ringan': {rusak_ringan_count}")

baik_count = df4[df4['Kondisi'] == 'Baik'].shape[0]
print(f"Total rows with Kondisi 'Baik': {baik_count}")

Total rows with Kondisi 'Rusak Berat': 80627
Total rows with Kondisi 'Rusak Ringan': 27444
Total rows with Kondisi 'Baik': 739081

In [ ]:
rusak_berat_usulhapus_count = df4[(df4['Kondisi'] == 'Rusak Berat') & (df4['Usul_Hapus'] == 'Ya')].shape[0]

print(f"Total rows with Kondisi 'Rusak Berat Usul Hapus': {rusak_berat_usulhapus_count}")

Total rows with Kondisi 'Rusak Berat Usul Hapus': 731

In [ ]:
display(df4)

In [ ]:
df4.info()

In [ ]:
columns_to_convert = ['No','Kode_Barang', 'NUP', 'Status_SBSN', 'Status_BMN_Idle', 'Jenis_Sertipikat', 'Kode_Kab_Kota', 'Kode_Provinsi', 'SBSK', 'Optimalisasi', 'Kode_KPKNL', 'Jenis_Identitas']

for col in columns_to_convert:
    if col in df4.columns:
        df4[col] = df4[col].astype(str).str.rstrip('.0')
    else:
        print(f"Warning: Column '{col}' not found in DataFrame.")

In [ ]:
df4.info()

In [ ]:
df4['Tanggal_PSP'] = pd.to_datetime(df4['Tanggal_PSP'], errors='coerce')

In [ ]:
display(df4['Jenis_BMN'].value_counts())

In [ ]:
display(df4.describe())

In [ ]:
display(df4.columns)

Index(['No', 'Jenis_BMN', 'Kode_Satker', 'Nama_Satker', 'Kode_Barang', 'NUP',
       'Nama_Barang', 'Status_BMN', 'Merk', 'Tipe', 'Kondisi', 'Umur_Aset',
       'Intra___Extra', 'Henti_Guna', 'Status_SBSN', 'Status_BMN_Idle',
       'Status_Kemitraan', 'BPYBDS', 'Usulan_Barang_Hilang',
       'Usulan_Barang_RB', 'Usul_Hapus', 'Hibah_DKTP', 'Konsensi_Jasa',
       'Properti_Investasi', 'Jenis_Dokumen', 'No_Dokumen', 'No_BPKP',
       'No_Polisi', 'Status_Sertifikasi', 'Jenis_Sertipikat', 'No_Sertifikat',
       'Nama', 'Tanggal_Buku_Pertama', 'Tanggal_Perolehan',
       'Tanggal_Pengapusan', 'Nilai_Perolehan_Pertama', 'Nilai_Mutasi',
       'Nilai_Perolehan', 'Nilai_Penyusutan', 'Nilai_Buku',
       'Luas_Tanah_Seluruhnya', 'Luas_Tanah_Untuk_Bangunan',
       'Luas_Tanah_Untuk_Sarana_Lingkungan', 'Luas_Lahan_Kosong',
       'Luas_Bangunan', 'Luas_Tapak_Bangunan', 'Luas_Pemanfataan',
       'Jumlah_Lantai', 'Jumlah_Foto', 'Status_Penggunaan', 'No_PSP',
       'Tanggal_PSP', 'Alamat', 'RT_RW', 'Kelurahan_Desa', 'Kecamatan',
       'Kab_Kota', 'Kode_Kab_Kota', 'Provinsi', 'Kode_Provinsi', 'Kode_Pos',
       'SBSK', 'Optimalisasi', 'Penghuni', 'Pengguna', 'Kode_KPKNL',
       'Uraian_KPKNL', 'Uraian_Kanwil_DJKN', 'Nama_K_L', 'Nama_E1',
       'Nama_Korwil', 'Kode_Register', 'Lokasi_Ruang', 'Jenis_Identitas',
       'No_Identitas', 'No_STNK', 'Nama_Pengguna', 'Status_PMK'],
      dtype='object')

In [ ]:
import pandas_gbq

In [ ]:
project_id = "primal-timing-458603-t4"
native_table_id = "MasterAsetBMNRB.MasterAset_BMNRB_29062026"

In [ ]:
pandas_gbq.to_gbq(df4, native_table_id, project_id=project_id, if_exists='replace')

print(f"Data successfully loaded into native BigQuery table: {native_table_id}")

-----------------SELESAI-----------------------------------

In [ ]:
columns_modified = []

for col in df_from_bq.columns:
    # Convert column to string type to safely check for '.0'
    df_from_bq[col] = df_from_bq[col].astype(str)

    # Check if any value in the column ends with '.0'
    if df_from_bq[col].str.endswith('.0').any():
        df_from_bq[col] = df_from_bq[col].str.rstrip('.0')
        columns_modified.append(col)

if columns_modified:
    print(f"Successfully removed '.0' from the following columns: {', '.join(columns_modified)}")
    print("Here's a preview of the modified columns:")
    display(df_from_bq[columns_modified].head())
else:
    print("No columns found with values ending in '.0'.")

In [ ]:
query = f"SELECT * FROM `{project_id}.{native_table_id}`"
df_from_bq = pandas_gbq.read_gbq(query, project_id=project_id)

print(f"Successfully imported {len(df_from_bq)} rows from BigQuery table: {native_table_id}")
display(df_from_bq.head())

In [ ]:
df_from_bq['No'] = df_from_bq['No'].astype(str).str.rstrip('.0')
df_from_bq['NUP'] = df_from_bq['NUP'].astype(str).str.rstrip('.0')

print("Columns 'No' and 'NUP' after removing '.0':")
display(df_from_bq[['No', 'NUP']].head())

In [ ]:
display(df_from_bq.head())

In [ ]:
pandas_gbq.to_gbq(df_from_bq, native_table_id, project_id=project_id, if_exists='replace')

print(f"Data successfully loaded into native BigQuery table: {native_table_id}")

In [ ]:
df_imipas_RB = df4[df4['Kondisi'].fillna('').str.contains('Berat')]
display(df_imipas_RB)